### ISSUE TITLE
Select relevant years only (1991-2020; 2041-2100)

### ISSUE THREAD

**Issue by irenebn** [KSSno/KiN2100#5]
Currently, all files in a directory are selected, which means that more years are processed than necessary.
IF the point is to generate indices for all files one time only, then this issue is not relevant. In that case, subsetting can be done later in the process. 

I will try do add this anyway, to save space.

Note, too, that the different RCMs span different years.

A few notes:
```
    echo "Filedir = " $filedir
    filelist=`ls $1`  # All files (years from 1961-2100) are listed in filelist. Then index computations loop over filelist.

     ls $1'/cnrm-r1i1p1-aladin_rcp26_eqm-sn2018v2005_rawbc_norway_1km_tas_daily_'{2071..2100}'.nc4'
     echo ls $1'/'$RCM'_rcp26_eqm-sn2018v2005_rawbc_norway_1km_'$VAR'_daily_'{2071..2100}'.nc4'
     filelist_subset=`ls $1'/'$RCM'_rcp26_eqm-sn2018v2005_rawbc_norway_1km_'$VAR'_daily_'{2071..2100}'.nc4'`
     echo "Subsetted Filelist = " $filelist_subset
     nbrfiles_subset=`echo $filelist_subset | wc -w`
```

**Comment by irenebn** [comment]
Notater fra scriptemøte 29. august 2023. Oskar, Sigrid, Irene.

# Forslag 1 (FALLER):  
Lage et ytre script for å kalle indeksberegningen:

for {1991..2020}; do
  ./calc_generalised_indices.sh VAR RCM YEAR
done


# Forslag 2 (GÅ VIDERE MED DENNE):

Beholde ett langt script, gi årstall som inputverdier.
 `./calc_generalised_indices.sh -var tas -rcm RCMLIST -scenario rcp45 -scenariobegin 2071 -scenarioend 2100 -refbegin 1991 -refend 2020`

 # Oskar prøver å finne ut hvordan argumentene kan generaliseres.
 https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash
 https://stackoverflow.com/questions/45421351/separating-flags-from-arguments-in-bash-script?rq=3
 ```
refbegin=$2 
 refend=$3
```
 Kan utvide med flere argumenter og defaultverdier:
```
 $scenario=RCP45
 $scenariobegin=2071
 $scenarioend=2100
```
```
    for yyyy in $( seq $refbegin $refend )   # seq $refstart $refend  # list chosen years
    do
	file=`ls $1/*$yyyy.nc4`        
        file=`basename $file`                   
```

(Vi fant en bedre måte å hente inn årstall, se over. Et tidlig alternativ var å hente inn årstall fra filnavnene:
echo filename | grep -Eo '[0-9]+.nc4$' | sed s/.nc4// | grep echo ../../EQM/noresm-r1i1p1-remo/tas/hist/noresm-r1i1p1-remo_hist_eqm-sn2018v2005_rawbc_norway_1km_tas_daily_2020.nc4 | grep -Eo '[0-9]+.nc4$' | sed s/.nc4//  )


La inn mulighet for å lagre output fra indeksberegning i tmp/$USER, men kun de filene vi trenger å slette til slutt.
```
mkdir -p $workdir
cd $workdir
mkdir -p tmp/$USER
```
Foreløpig lagres kun mergetime-filer i tmp/$USER (beholder heller enkeltårene). Kan legge andre ting man trenger å slette inn der.
```
cdo mergetime $workdir/$RCM/$VAR/*'_tasmax_annual-mean.nc'   $workdir/tmp/$USER/'tasmax_annual-mean_mergetime_'$refbegin'-'$refend'.nc'

cdo timmean growing_season_$refbegin-$refend.nc         growing_season_30yearmean_2071-2100.nc
cdo timmean growing_season_$scenbegin-$scenend.nc    growing_season_30yearmean_1991-2020.nc

cdo sub growing_season_30yearmean_2071-2100.nc growing_season_30yearmean_1991-2020.nc difference_in_growing_seas.nc

rm tmp/$USER/mergetime*
```

**Comment by sigridjb** [comment]
Jeg har funnet en løsning på "finne ut hvordan argumentene kan generaliseres." Koden er klar til å legges inn i hovedskriptet, men venter med dette.

**Comment by irenebn** [comment]
Sigrid og Oskar fant lurt måte å velge ut år i argumentet til funksjonen.
